#!/bin/sh
# Installs pip requirements
set -e
cd "$(dirname $(readlink -f "$0"))/.."

pip install --compile --no-cache-dir --prefer-binary -r requirements.txt

REQUIREMENTS=$(python -m homecontrol.scripts.module_requirements)
TEST_REQUIREMENTS=$(python -m homecontrol.scripts.module_requirements -t)

if [ -n "$REQUIREMENTS" ]; then
    pip install --compile --no-cache-dir --prefer-binary $REQUIREMENTS
fi
if [ -n "$TEST_REQUIREMENTS" ]; then
    pip install --compile --no-cache-dir -i https://test.pypi.org/simple/ --prefer-binary $TEST_REQUIREMENTS
fi
